name: update compose files
run-name: update compose files

on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Set Git credentials
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Install project
        run: uv pip install -e .

      - name: Run Python script
        run: uv run python -m composekit.generate
        env:
          CONTAINERS_FOLDER: ${{ vars.CONTAINERS_FOLDER }}
          COMPOSES_FOLDER: ${{ vars.COMPOSES_FOLDER }}
          NETWORK_NAME: ${{ vars.NETWORK_NAME }}
          SUBNET: ${{ vars.SUBNET }}
          USE_FULL_DIRECTORY: ${{ vars.USE_FULL_DIRECTORY }}
          BIND_PATH: ${{ vars.BIND_PATH }}
          OUTPUT: ${{ vars.OUTPUT }}

      - name: Push changes
        run: git push
