name: update images
run-name: update images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */8 * * *'

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
      UV_LINK_MODE: copy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Restore uv cache
        uses: actions/cache@v5
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-python${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-python${{ steps.setup-python.outputs.python-version }}-
            uv-${{ runner.os }}-

      - name: Set Git credentials
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Install project
        run: uv pip install -e .

      - name: Run Python script
        run: uv run python -m composekit.update
        env:
          CONTAINERS_FOLDER: ${{ vars.CONTAINERS_FOLDER }}
          COMPOSES_FOLDER: ${{ vars.COMPOSES_FOLDER }}
          NETWORK_NAME: ${{ vars.NETWORK_NAME }}
          SUBNET: ${{ vars.SUBNET }}
          USE_FULL_DIRECTORY: ${{ vars.USE_FULL_DIRECTORY }}
          BIND_PATH: ${{ vars.BIND_PATH }}
          OUTPUT: ${{ vars.OUTPUT }}

      - name: Push changes
        run: git push
